// libraries/resolut/packages/qwik/src/components/input/select/select.component.tsx
import { component$ } from '@builder.io/qwik'
import Input from '../input/input.component'

const Select = component$(({ options, ...props }: Resolut.Component.SelectProps) => {
    return (
        <Input tag="select" element="select" {...props}>
            {options &&
                options.map(({ value, name }) => (
                    <option value={value} key={name + value} class="resolut-option">
                        {name}
                    </option>
                ))}
        </Input>
    )
})

export default Select

// apps/cms/client/desktop/src/renderer/components/select/select.component.tsx
import useSelectStyles from './select.component.styles';
import SelectComponent from './select.component.types';

const Select: SelectComponent = ({ className, options, label, name, ...props }) => {
    const styles = useSelectStyles();

    return (
        <>
            <label className={styles.label} htmlFor={name}>
                {label}
            </label>
            <select name={name} className={`${className} ${styles.select}`} {...props}>
                {options.map((option, index) => (
                    <option key={index} value={option.value}>
                        {option.label}
                    </option>
                ))}
            </select>
        </>
    );
};

export default Select;
