// libraries/resolut/packages/qwik/src/components/layout/field/field.component.tsx
import { component$ } from '@builder.io/qwik'
import Layout from '../layout/layout.component'

const Field = component$(({ message, ...props }: Resolut.Component.FieldProps) => {
    return <Layout tag="field" {...Utils.setAttributes({ message })} element="div" {...props}></Layout>
})

export default Field

// libraries/resolut/packages/solid/src/components/layout/field/field.component.tsx
import Layout from '../layout/layout.component'

const Field: Resolut.Component<Resolut.Component.FieldProps> = ({ message, children, ref, ...props }) => {
    return (
        <Layout ref={ref} tag="field" {...Utils.setAttributes({ message })} element="div" {...props}>
            {children}
        </Layout>
    )
}

export default Field
