// libraries/resolut/packages/solid/src/components/layout/section/section.component.tsx
import Layout from '../layout/layout.component'

const Section: Resolut.Component<Resolut.Component.SectionProps> = ({ children, ref, ...props }) => {
    return (
        <Layout {...props} ref={ref} element="section" tag="section">
            {children}
        </Layout>
    )
}

export default Section

// libraries/resolut/packages/qwik/src/components/layout/section/section.component.tsx
import { component$ } from '@builder.io/qwik'
import Layout from '../layout/layout.component'

const Section = component$(({ ...props }: Resolut.Component.SectionProps) => {
    return (
        <Layout {...props} element="section" tag="section">
            <Slot />
        </Layout>
    )
})

export default Section
