// libraries/resolut/packages/qwik/src/components/layout/form/form.component.tsx
import { component$ } from '@builder.io/qwik'
import Layout from '../layout/layout.component'

const Form = component$(({ onSubmit, preventDefault, ...props }: Resolut.Component.FormProps) => {
    // const handleSubmit = (event: any) => {
    //     preventDefault === true && event.preventDefault()

    //     console.log('Submitting...')

    //     onSubmit && onSubmit(event)
    // }

    return (
        <Layout tag="form" element="form" {...props}>
            <Slot />
        </Layout>
    )
})

export default Form

// libraries/resolut/packages/react/src/components/layout/form/form.component.tsx
import Layout from '../layout/layout.component'

const Form = Resolut.create<HTMLFormElement, Resolut.Component.FormProps>(
    (
        { children, onSubmit, preventDefault, /** @inject ref, **/ ...props } /** @remove start **/,
        ref /** @remove end **/
    ) => {
        const handleSubmit = (event: Resolut.Events.SubmitEvent) => {
            preventDefault === true && event.preventDefault()

            console.log('Submitting...')

            onSubmit && onSubmit(event)
        }

        return (
            <Layout ref={ref} onSubmit={handleSubmit} tag="form" element="form" {...props}>
                {children}
            </Layout>
        )
    }
)

export default Form
