// apps/prometheus/client/src/renderer/components/navigation/navigation.component.tsx
import useNavigationStyles from './navigation.component.styles';
import NavigationComponent from './navigation.component.types';

const Navigation: NavigationComponent = () => {
    const styles = useNavigationStyles();

    const items = [
        { path: '/orders', name: 'Ordrer' },
        { path: '/webshop', name: 'Webshop' },
        { path: '/accounting', name: 'Regnskab' },
        { path: '/customers', name: 'Kundekartotek' },
        { path: '/employees', name: 'Medarbejdere' },
    ];

    return (
        <nav className={styles.navigation}>
            {items.map((item, index) => (
                <a key={index} href={item.path} className={styles.anchor}>
                    {item.name}
                </a>
            ))}
        </nav>
    );
};

export default Navigation;

// projects/webshop/client/desktop/frontend/src/app/components/navigation/navigation.component.ts
import { Component } from '@angular/core';
import { Item } from '../../types/item';

@Component({
    selector: 'app-navigation',
    templateUrl: './navigation.component.html',
    styleUrls: ['./navigation.component.sass'],
})
export class NavigationComponent {
    items: Item[] = [
        { path: '/dashboard/orders', name: 'Ordrer' },
        { path: '/dashboard/webshop', name: 'Webshop' },
        { path: '/dashboard/accounting', name: 'Regnskab' },
        { path: '/dashboard/customers', name: 'Kundekartotek' },
        { path: '/dashboard/employees', name: 'Medarbejdere' },
    ];
}

<nav>
    <a *ngFor="let item of items" [routerLink]="item.path" routerLinkActive="active">{{ item.name }}</a>
</nav>
