// apps/nexus/client/desktop/src/components/select.component.tsx
const Select = ({
    column,
    row,
    name,
    children,
    label,
    value,
    defaultValue,
    onChange = () => null
}: {
    column: string
    row: string
    name: string
    label: string
    children: JSX.Element
    value?: string
    defaultValue?: string
    onChange?: React.ChangeEventHandler<HTMLSelectElement>
}) => {
    return (
        <div style={{ gridColumn: column, gridRow: row }} className="flex flex-col gap-2">
            <label htmlFor={name}>{label}</label>
            <select
                value={value || defaultValue}
                id={name}
                name={name}
                onChange={onChange}
                className="border-gray-200 w-full height-12"
            >
                {children}
            </select>
        </div>
    )
}

export default Select

// apps/nexus/client/src/components/select.component.tsx
import { JSX } from 'solid-js'

const Select = ({
    column,
    row,
    name,
    children,
    label,
    value,
    defaultValue,
    onChange = () => null
}: {
    column: string
    row: string
    name: string
    label: string
    children: JSX.Element
    value?: string
    defaultValue?: string
    onChange?: (event: Event) => void
}) => {
    return (
        <div flex flex-column gap-05 style={{ 'grid-column': column, 'grid-row': row }}>
            <label for={name}>{label}</label>
            <select value={value || defaultValue} border-grey-200 h-3 w-full id={name} name={name} onChange={onChange}>
                {children}
            </select>
        </div>
    )
}

export default Select
