// libraries/resolut/packages/solid/src/components/input/text/text.component.tsx
import Input from '../input/input.component'

const Text: Resolut.Component<Resolut.Component.TextProps> = ({ email, password, tel, number, url, ref, ...props }) => {
    return (
        <Input
            tag="text"
            element="input"
            type={Utils.setValueFromBoolean({ email, password, tel, number, url }) || 'text'}
            ref={ref}
            {...props}
        />
    )
}

export default Text

// libraries/resolut/packages/qwik/src/components/input/text/text.component.tsx
import { component$ } from '@builder.io/qwik'
import Input from '../input/input.component'

const Text = component$(({ email, password, tel, number, url, ...props }: Resolut.Component.TextProps) => {
    return (
        <Input
            tag="text"
            element="input"
            type={Utils.setValueFromBoolean({ email, password, tel, number, url }) || 'text'}
            {...props}
        />
    )
})

export default Text
