// libraries/resolut/packages/solid/src/components/layout/article/article.component.tsx
import Layout from '../layout/layout.component'

const Article: Resolut.Component<Resolut.Component.ArticleProps> = ({ children, ref, ...props }) => {
    return (
        <Layout {...props} ref={ref} element="article" tag="article">
            {children}
        </Layout>
    )
}

export default Article

// libraries/resolut/packages/qwik/src/components/layout/article/article.component.tsx
import { component$ } from '@builder.io/qwik'
import Layout from '../layout/layout.component'

const Article = component$(({ ...props }: Resolut.Component.ArticleProps) => {
    return (
        <Layout {...props} element="article" tag="article">
            <Slot />
        </Layout>
    )
})

export default Article
