// libraries/resolut/packages/qwik/src/components/layout/main/main.component.tsx
import { component$ } from '@builder.io/qwik'
import Layout from '../layout/layout.component'

const Main = component$(({ ...props }: Resolut.Component.MainProps) => {
    return (
        <Layout {...props} element="main" tag="main">
            <Slot />
        </Layout>
    )
})

export default Main

// libraries/resolut/packages/react/src/components/layout/main/main.component.tsx
import Layout from '../layout/layout.component'

const Main = Resolut.create<HTMLElement, Resolut.Component.MainProps>(
    ({ children, /** @inject ref, **/ ...props } /** @remove start **/, ref /** @remove end **/) => {
        return (
            <Layout {...props} ref={ref} element="main" tag="main">
                {children}
            </Layout>
        )
    }
)

export default Main
