// libraries/resolut/packages/solid/src/components/typography/label/label.component.tsx
import Typography from '../typography/typography.component'

const Label: Resolut.Component<Resolut.Component.LabelProps> = ({
    children,
    for: htmlFor,
    required = false,
    ref,
    ...props
}) => {
    return (
        <Typography
            ref={ref}
            for={htmlFor}
            tag="label"
            element="label"
            {...props}
            {...Utils.setAttributes({ required })}
        >
            {children}
        </Typography>
    )
}

export default Label

// libraries/resolut/packages/qwik/src/components/typography/label/label.component.tsx
import { component$ } from '@builder.io/qwik'
import Typography from '../typography/typography.component'

const Label = component$(({ for: htmlFor, required = false, ...props }: Resolut.Component.LabelProps) => {
    return (
        <Typography for={htmlFor} tag="label" element="label" {...props} {...Utils.setAttributes({ required })}>
            <Slot />
        </Typography>
    )
})

export default Label
