// libraries/resolut/packages/qwik/src/components/typography/paragraph/paragraph.component.tsx
import { component$ } from '@builder.io/qwik'
import Typography from '../typography/typography.component'

const Paragraph = component$(({ ...props }: Resolut.Component.ParagraphProps) => {
    return (
        <Typography tag="paragraph" element="p" {...props}>
            <Slot />
        </Typography>
    )
})

export default Paragraph

// libraries/resolut/packages/solid/src/components/typography/paragraph/paragraph.component.tsx
import Typography from '../typography/typography.component'

const Paragraph: Resolut.Component<Resolut.Component.ParagraphProps> = ({ children, ref, ...props }) => {
    return (
        <Typography tag="paragraph" element="p" ref={ref} {...props}>
            {children}
        </Typography>
    )
}

export default Paragraph
