// libraries/resolut/packages/qwik/src/components/layout/footer/footer.component.tsx
import { component$ } from '@builder.io/qwik'
import Layout from '../layout/layout.component'

const Footer = component$(({ ...props }: Resolut.Component.FooterProps) => {
    return (
        <Layout tag="footer" element="footer" {...props}>
            <Slot />
        </Layout>
    )
})

export default Footer

// libraries/resolut/packages/react/src/components/layout/footer/footer.component.tsx
import Layout from '../layout/layout.component'

const Footer = Resolut.create<HTMLElement, Resolut.Component.FooterProps>(({ children, ...props }, ref) => {
    return (
        <Layout tag="footer" element="footer" ref={ref} {...props}>
            {children}
        </Layout>
    )
})

export default Footer
