// libraries/resolut/packages/qwik/src/components/typography/link/link.component.tsx
import { component$ } from '@builder.io/qwik'
import Typography from '../typography/typography.component'

const Link = component$(({ underline = true, ...props }: Resolut.Component.LinkProps) => {
    return (
        <Typography tag="link" element="a" {...Utils.setAttributes({ underline })} {...props}>
            <Slot />
        </Typography>
    )
})

export default Link

// libraries/resolut/packages/react/src/components/typography/link/link.component.tsx
import Typography from '../typography/typography.component'

const Link = Resolut.create<HTMLAnchorElement, Resolut.Component.LinkProps>(
    ({ underline = true, children, /** @inject ref, **/ ...props } /** @remove start **/, ref /** @remove end **/) => {
        return (
            <Typography ref={ref} tag="link" element="a" {...Utils.setAttributes({ underline })} {...props}>
                {children}
            </Typography>
        )
    }
)

export default Link
