// apps/prometheus/client/src/renderer/components/list/list.component.tsx
import ListComponent from './list.component.types';
import { Link } from 'react-router-dom';
import useListStyles from './list.component.styles';

const List: ListComponent = ({ title, items }) => {
    const styles = useListStyles();

    return (
        <ul className={styles.list}>
            {items.map((item, index) => (
                <li key={index} className={styles.item}>
                    <Link className={styles.title} to={item.path}>
                        {item.name}
                    </Link>
                </li>
            ))}
        </ul>
    );
};

export default List;

// projects/webshop/client/desktop/frontend/src/app/components/list/list.component.ts
import { Component, Input } from '@angular/core';
import { Item } from '../../types/item';

@Component({
    selector: 'app-list',
    templateUrl: './list.component.html',
    styleUrls: ['./list.component.sass'],
})
export class ListComponent {
    @Input()
    title!: string;

    @Input()
    items!: Item[];
}

<ul>
    <h4>{{ title }}</h4>
    <li *ngFor="let item of items">
        <a [routerLink]="item.path">{{ item.name }}</a>
    </li>
</ul>
