// libraries/resolut/packages/solid/src/components/input/select/select.component.tsx
import { For } from 'solid-js'
import Input from '../input/input.component'

const Select: Resolut.Component<Resolut.Component.SelectProps> = ({ options, ref, ...props }) => {
    return (
        <Input tag="select" element="select" ref={ref} {...props}>
            <For each={options}>
                {({ value, name }) => (
                    <option class="resolut-option" value={value}>
                        {name}
                    </option>
                )}
            </For>
        </Input>
    )
}

export default Select

// libraries/resolut/packages/qwik/src/components/input/select/select.component.tsx
import { component$ } from '@builder.io/qwik'
import Input from '../input/input.component'

const Select = component$(({ options, ...props }: Resolut.Component.SelectProps) => {
    return (
        <Input tag="select" element="select" {...props}>
            {options &&
                options.map(({ value, name }) => (
                    <option value={value} key={name + value} class="resolut-option">
                        {name}
                    </option>
                ))}
        </Input>
    )
})

export default Select
