// libraries/resolut/packages/react/src/components/input/select/select.component.tsx
import Input from '../input/input.component'

const Select = Resolut.create<HTMLSelectElement, Resolut.Component.SelectProps>(
    ({ options, /** @inject ref, **/ ...props } /** @remove start **/, ref /** @remove end **/) => {
        return (
            <Input tag="select" element="select" ref={ref} {...props}>
                {options &&
                    options.map(({ value, name }) => (
                        <option
                            /** @inject class="resolut-option" **/
                            value={value}
                            /** @remove start **/
                            key={name + value}
                            className="resolut-option"
                            /** @remove end **/
                        >
                            {name}
                        </option>
                    ))}
            </Input>
        )
    }
)

export default Select

// libraries/resolut/packages/qwik/src/components/input/select/select.component.tsx
import { component$ } from '@builder.io/qwik'
import Input from '../input/input.component'

const Select = component$(({ options, ...props }: Resolut.Component.SelectProps) => {
    return (
        <Input tag="select" element="select" {...props}>
            {options &&
                options.map(({ value, name }) => (
                    <option value={value} key={name + value} class="resolut-option">
                        {name}
                    </option>
                ))}
        </Input>
    )
})

export default Select
