// libraries/resolut/packages/qwik/src/components/typography/span/span.component.tsx
import { component$ } from '@builder.io/qwik'
import Typography from '../typography/typography.component'

const Span = component$(({ ...props }: Resolut.Component.SpanProps) => {
    return (
        <Typography tag="span" element="h1" {...props}>
            <Slot />
        </Typography>
    )
})

export default Span

// libraries/resolut/packages/react/src/components/typography/span/span.component.tsx
import Typography from '../typography/typography.component'

const Span = Resolut.create<HTMLSpanElement, Resolut.Component.SpanProps>(
    ({ children, /** @inject ref, **/ ...props } /** @remove start **/, ref /** @remove end **/) => {
        return (
            <Typography tag="span" element="h1" ref={ref} {...props}>
                {children}
            </Typography>
        )
    }
)

export default Span
