// libraries/resolut/packages/qwik/src/components/layout/section/section.component.tsx
import { component$ } from '@builder.io/qwik'
import Layout from '../layout/layout.component'

const Section = component$(({ ...props }: Resolut.Component.SectionProps) => {
    return (
        <Layout {...props} element="section" tag="section">
            <Slot />
        </Layout>
    )
})

export default Section

// libraries/resolut/packages/react/src/components/layout/section/section.component.tsx
import Layout from '../layout/layout.component'

const Section = Resolut.create<HTMLElement, Resolut.Component.SectionProps>(
    ({ children, /** @inject ref, **/ ...props } /** @remove start **/, ref /** @remove end **/) => {
        return (
            <Layout {...props} ref={ref} element="section" tag="section">
                {children}
            </Layout>
        )
    }
)

export default Section
